


print("2 xícaras de farinha de trigo")
input()
print("1 xícara de açúcar")
input()
print("1/2 xícara de cacau em po")
input()
print("1 colher de chá de fermento em pó")
input()
print("I colher de chá de bicarbonato de sódio")
input()
print("V2 colher de chá de sal")
input()
print("2 ovos")
input()
print("1 xícara de leite")
input()
print("1/2 xícara de óleo vegetal")
input()
print("2 colheres de cha de extrato de baunilha")
input()
print("1 xícara de água fervente")
input()
print("Modo de preparo:")
input()
print("Pré-aqueça o forno a 180°C. Unte uma forma de bolo com manteiga e farinha, ou forre-a com papel manteiga 1")
input()
print("Em uma tigela grande, peneire a farinha de trigo, o açúcar, o cacau em po, o fermento em pó, o bicarbonato de sódio e o sal. Misture bem. 2")
input()
print("3 Em outra tigela, bata os ovos levemente. Adicione o leite, a dien vegetal e o extrato de baunilha. Misture bem")
input()
print("4. Despeje os ingredientes liquidos na mistura de ingredientes secos e mexa até que tudo esteja bem combinado")
input()
print("5 Adicione a água fervente à massa e misture até que a massa fique homogénea. A massa ficará líquida, mas é normal.")
input()
print("6 Despeje a massa na forma preparada e leve ao forno pré-aquecido.")
input()
print("7 Asse por cerca de 30-35 minutos, ou até que um palito inserido no centro do bolo saia limpo")
input()
print("8")
input()
print("Retire o bolo do forno e deixe esfriar na forma por alguns minutos Em seguida, transfira para uma grade de resfriamento para esfriar completamente.")
input()
print("9")
input()
print("Depois de esfriar, você pode servir a bolo simples ou decorá-lo com cobertura de sua preferência, como ganache de chocolate ou glacé de chocolate")
input()
